/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Console.Agenda;
import Console.Cliente;
import Console.Produtos;
import ConsoleDAO.AgendaDAO;
import ConsoleDAO.ClienteDAO;
import ConsoleDAO.ProdutosDAO;
import FramesCliente.CadastroCliente;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class FrameManicure extends javax.swing.JFrame {

    /**
     * Creates new form FrameManicure
     */
    public FrameManicure() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgenda = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtProcedimento = new javax.swing.JTextField();
        EditarStatus = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btPesquisarAgenda = new javax.swing.JButton();
        NovoAgendamento = new javax.swing.JButton();
        btEditarAgenda = new javax.swing.JButton();
        btExcluirAgenda = new javax.swing.JButton();
        txtCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        btLimpar = new javax.swing.JButton();
        btPesquisarCliente = new javax.swing.JButton();
        btAdicionarCliente = new javax.swing.JButton();
        btEditarCliente = new javax.swing.JButton();
        btExcluirCliente = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btLimpar1 = new javax.swing.JButton();
        btAdicionar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Agendamentos"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAgenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblAgenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblAgenda);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 669, 470));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Cliente :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Procedimento :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtProcedimento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtProcedimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 297, -1));

        EditarStatus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EditarStatus.setText("Editar Status");
        EditarStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarStatusActionPerformed(evt);
            }
        });
        jPanel1.add(EditarStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, -1, 30));

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 110, -1));

        btPesquisarAgenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btPesquisarAgenda.setText("Pesquisar");
        btPesquisarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarAgendaActionPerformed(evt);
            }
        });
        jPanel1.add(btPesquisarAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        NovoAgendamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NovoAgendamento.setText("Novo Agendamento");
        NovoAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoAgendamentoActionPerformed(evt);
            }
        });
        jPanel1.add(NovoAgendamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        btEditarAgenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btEditarAgenda.setText("Editar");
        btEditarAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarAgendaActionPerformed(evt);
            }
        });
        jPanel1.add(btEditarAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 110, -1));

        btExcluirAgenda.setText("Excluir");
        btExcluirAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirAgendaActionPerformed(evt);
            }
        });
        jPanel1.add(btExcluirAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 110, -1));

        txtCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 297, -1));

        jLabel2.setText("AGENDAMENTOS :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 153, 650, 10));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblClientes);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 204, 500, 468));
        jPanel2.add(txtNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 46, 204, -1));

        jLabel4.setText("Nome :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, -1, -1));
        jPanel2.add(txtGmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 46, 204, -1));

        jLabel5.setText("Gmail :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 24, -1, -1));

        jLabel6.setText("Telefone :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 74, -1, -1));
        jPanel2.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 96, 204, -1));

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        jPanel2.add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        btPesquisarCliente.setText("Pesquisar");
        btPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btPesquisarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, -1, -1));

        btAdicionarCliente.setText("Adicionar");
        btAdicionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btAdicionarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        btEditarCliente.setText("Editar");
        btEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btEditarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        btExcluirCliente.setText("Excluir");
        btExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirClienteActionPerformed(evt);
            }
        });
        jPanel2.add(btExcluirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 490, 20));

        jLabel12.setText("CLIENTES :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Produtos")));
        jPanel3.setPreferredSize(new java.awt.Dimension(558, 641));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tblProdutos);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 188, 540, 475));

        jLabel7.setText("Nome :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        jPanel3.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, -1));

        jLabel8.setText("Marca :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));
        jPanel3.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 140, -1));

        jLabel9.setText("Categoria");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));
        jPanel3.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 140, -1));

        jLabel10.setText("Quantidade :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        jPanel3.add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, -1));

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        jPanel3.add(btPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        jLabel11.setText("PRODUTOS :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 530, 20));

        btLimpar1.setText("Limpar");
        btLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btLimpar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });
        jPanel3.add(btAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        jPanel3.add(btEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel3.add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(194, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditarStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarStatusActionPerformed
        int linhaSelecionada = tblAgenda.getSelectedRow();

        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(this,"Selecione um agendamento na tabela primeiro.");
            return ;
        }

        // Pega o ID do agendamento e o status atual
        int idAgenda = (int) tblAgenda.getValueAt(linhaSelecionada,0);
        String statusAtual = tblAgenda.getValueAt(linhaSelecionada,7).toString();

        // Altera o status de sim para não e vice-versa
        String novoStatus = statusAtual.equalsIgnoreCase("Sim")? "Não" : "Sim";

        int confirma = JOptionPane.showConfirmDialog(this,
            "Deseja alterar o status do agendamento : "+idAgenda+" Para "+novoStatus+" ?",
            "Confirmar Alteração",JOptionPane.YES_NO_OPTION);

        if(confirma == JOptionPane.YES_NO_OPTION){
            try{
                AgendaDAO dao = new AgendaDAO();
                dao.atualizarStatus(idAgenda, novoStatus);

                JOptionPane.showMessageDialog(this,"Status atualizado com sucesso !");

                preencherTabelaAgenda(txtCliente.getText(), txtProcedimento.getText());

            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Erro ao atualizar status: "+ e.getMessage());
            }
        }
    }//GEN-LAST:event_EditarStatusActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtCliente.setText("");
        txtProcedimento.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btPesquisarAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarAgendaActionPerformed
        String cliente = txtCliente.getText();
        String procedimento = txtProcedimento.getText();
        preencherTabelaAgenda(cliente, procedimento);
    }//GEN-LAST:event_btPesquisarAgendaActionPerformed

    private void NovoAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoAgendamentoActionPerformed
        CadastroAgenda novaAgenda = new CadastroAgenda();
        novaAgenda.setVisible(true);
    }//GEN-LAST:event_NovoAgendamentoActionPerformed

    private void btEditarAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarAgendaActionPerformed
         // Verifdica se há alguma linha selecionada
        int linhaSelecionada = tblAgenda.getSelectedRow();
        
        if(linhaSelecionada >= 0 ){
            try{
                // Pega o ID da primeira coluna (linha selecionada, coluna 0)
                int id = Integer.parseInt(tblAgenda.getValueAt(linhaSelecionada, 0 ).toString());
                
                // Busca o objeto Agendamento completo no banco de dado pelo ID
                AgendaDAO dao = new AgendaDAO();
                Agenda agendamentoSeleionado = dao.obter(id);
                
                // Abre a tela de Cadastro/ Edição e envia os dados para preenchimento
                CadastroAgenda cadastro = new CadastroAgenda();
                cadastro.preencherEdicao(agendamentoSeleionado);
                cadastro.setVisible(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Erro ao manicure : "+e.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(this,"Por favor, selecione um agendamento na tela para editar. ");
        }
    }//GEN-LAST:event_btEditarAgendaActionPerformed

    private void btExcluirAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirAgendaActionPerformed
        try{
            if(tblAgenda.getSelectedRow() >= 0 ){ // Verifica se tem algum objeto selecionado
                String id = tblAgenda.getValueAt(tblAgenda.getSelectedRow(), 0).toString();

                // Janela de confirmação
                int resposta = JOptionPane.showConfirmDialog(this,"Deseja mesmo excluir o registro : "+id+" ?");
                if(resposta == 0){
                    AgendaDAO agendaDao = new AgendaDAO();
                    agendaDao.excluir(Integer.parseInt(id));
                    JOptionPane.showMessageDialog(this,"Registro excluído com sucesso !");
                    btPesquisarActionPerformed(evt);
                }

            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Ocorreu uma falha : "+e.getMessage());
        }
    }//GEN-LAST:event_btExcluirAgendaActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // LIMPAS OS CAMPOS
        txtNomeCliente.setText("");
        txtTelefone.setText("");
        txtGmail.setText("");
    }//GEN-LAST:event_btLimparActionPerformed

    private void btPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarClienteActionPerformed
        try{
            ClienteDAO clienteDao = new ClienteDAO();
            String nome = txtNomeCliente.getText();
            String gmail = txtGmail.getText();
            String telefone = txtTelefone.getText();

            List<Cliente> cliente = clienteDao.listar(nome,gmail,telefone);

            preencherTabelaClientes(cliente);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Ocoreeu uma falha: \n"+e.getMessage());
        }
    }//GEN-LAST:event_btPesquisarClienteActionPerformed

    private void btAdicionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarClienteActionPerformed
        CadastroCliente novaPessoa = new CadastroCliente();
        novaPessoa.setVisible(true);
    }//GEN-LAST:event_btAdicionarClienteActionPerformed

    private void btEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarClienteActionPerformed
        // Verificar se alguma linha da tabela foi selecionada
        int linhaSelecionada = tblClientes.getSelectedRow();

        if(linhaSelecionada >= 0){
            try{
                // Pega o ID da primeira coluna (linha selecionada, coluna 0)
                int id = Integer.parseInt(tblClientes.getValueAt(linhaSelecionada, 0).toString());

                // Busca o objeto Manicure completo no banco de dados pelo ID
                ClienteDAO dao  = new ClienteDAO();
                Cliente manicureSelecionada = dao.obter(id);

                // Abre a tela de Cadastro/Edição e envia os dados para preenchimento
                CadastroCliente cadastro = new CadastroCliente();
                cadastro.preencherEdicao(manicureSelecionada);
                cadastro.setVisible(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Erro ao selecionar manicure : "+ e.getMessage());
            }
        }else {
            JOptionPane.showMessageDialog(this,"Por favor, selecionar uma manicure na tela para editar.");
        }
    }//GEN-LAST:event_btEditarClienteActionPerformed

    private void btExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirClienteActionPerformed
        try{
            if(tblClientes.getSelectedRow() >= 0){// verifica se há algo selecionado na tabela
                String id = tblClientes.getValueAt(tblClientes.getSelectedRow(), 0).toString();

                // Janela de confirmação
                int resposta = JOptionPane.showConfirmDialog(this,"Deseja mesmo excluir o registro "+id+" ?");
                if (resposta == 0) // ) - Yes, 1 - no, 2 - cancel
            {
                // Realizando a exclusão dos dados
                ClienteDAO cliente = new ClienteDAO();
                cliente.excluir(Integer.parseInt(id));
                JOptionPane.showMessageDialog(this,"Registro excluido com sucesso !");
                // atualizadn a tabela
                btPesquisarActionPerformed(evt);
            }

        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Ocorreu uma falha : \n"+e.getMessage());
        }
    }//GEN-LAST:event_btExcluirClienteActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        try{
            ProdutosDAO dao = new ProdutosDAO();
            String nome = txtNome.getText();
            String marca = txtMarca.getText();
            String categoria = txtCategoria.getText();
            String qtdTexto = txtQuantidade.getText().trim();
            Integer quantidade = qtdTexto.isEmpty() ? null : Integer.parseInt(qtdTexto);

            List<Produtos> produtos = dao.listar(nome,marca,categoria,quantidade);

            preencherTabelaProdutos(produtos);

        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Ocoreeu uma falha: \n"+e.getMessage());
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpar1ActionPerformed
        // LIMPAS OS CAMPOS
        txtNome.setText("");
        txtQuantidade.setText("");
        txtMarca.setText("");
        txtCategoria.setText("");
    }//GEN-LAST:event_btLimpar1ActionPerformed

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        CadastroProdutos novoProduto = new CadastroProdutos();
        novoProduto.setVisible(true);
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // Verificar se alguma linha da tabela foi selecionada
        int linhaSelecionada = tblProdutos.getSelectedRow();

        if(linhaSelecionada >= 0){
            try{
                // Pega o ID da primeira coluna (linha selecionada)
                int id = Integer.parseInt(tblProdutos.getValueAt(linhaSelecionada, 0).toString());

                // Busca o produto completo no banco de dados pelo ID
                ProdutosDAO dao = new ProdutosDAO();
                Produtos produtoSelecionado = dao.obter(id);

                // Abre a tela de cadastro de produtos e envia os dados para preencher
                CadastroProdutos cadastro = new CadastroProdutos();
                cadastro.preencherEdicao(produtoSelecionado);
                cadastro.setVisible(true);

            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Erro ao selecionar o produto : "+e.getMessage());
            }

        }else{
            JOptionPane.showMessageDialog(this,"Por favor, selecionar um produto na tabela de produtos para editar");
        }

    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        try{
            if(tblProdutos.getSelectedRow() >= 0){ // verificar se algo foi selecionado na tabela
                String id = tblProdutos.getValueAt(tblProdutos.getSelectedRow(),0).toString();

                // Janela de confirmação
                int resposta = JOptionPane.showConfirmDialog(this,"Deseja mesmo excluir o registro : "+id+" ?");
                if (resposta == 0) // 0 - Yes, 1 - no, 2- cancel
                {
                    // Realizando a exclusão dos dados
                    ProdutosDAO dao = new ProdutosDAO();
                    dao.excluir(Integer.parseInt(id));
                    JOptionPane.showMessageDialog(this,"Registro excluido com sucesso !");

                    // Atualizando a tabela
                    btPesquisarActionPerformed(evt);

                }

            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Ocorreu uma falha :\n "+e.getMessage());
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameManicure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameManicure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameManicure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameManicure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameManicure().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarStatus;
    private javax.swing.JButton NovoAgendamento;
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btAdicionarCliente;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btEditarAgenda;
    private javax.swing.JButton btEditarCliente;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btExcluirAgenda;
    private javax.swing.JButton btExcluirCliente;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btLimpar1;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btPesquisarAgenda;
    private javax.swing.JButton btPesquisarCliente;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tblAgenda;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtGmail;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtProcedimento;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables



// Preencher Tabela de Agendamentos
    private void preencherTabelaAgenda(String filtroCliente, String filtroProcedimento){
        DefaultTableModel model = (DefaultTableModel) tblAgenda.getModel();
        model.setRowCount(0);
        
        model.setColumnIdentifiers(new String[]{
            "ID","Data","Horário","Cliente","Manicure","Serviço","Valor","Reallizado"
        });
        
        try {
            AgendaDAO dao = new AgendaDAO();
            
            // Tenta listar enviando os filtros digitados
            List<Agenda> lista = dao.listar(filtroCliente, filtroProcedimento);

            SimpleDateFormat sdfData = new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat sdfHora = new SimpleDateFormat("HH:mm");

            for (Agenda a : lista) {
                String dataStr = (a.getAgendamento() != null) ? sdfData.format(a.getAgendamento()) : "";
                String horaStr = (a.getHorario() != null) ? sdfHora.format(a.getHorario()) : "";
                String clienteStr = (a.getCliente() != null) ? a.getCliente().getNome() : "";
                String manicureStr = (a.getManicure() != null) ? a.getManicure().getNome() : "";
                String servicoStr = (a.getServico() != null) ? a.getServico().getProcedimento() : "";
                String valorStr = (a.getServico() != null && a.getServico().getValor() != null) 
                        ? String.format("R$ %.2f", a.getServico().getValor()) : "R$ 0,00";

                
                // atualizar se o agendamento foi concluido ou não
                String realizadoStr = (a.getRealizado() != null && !a.getRealizado().isEmpty())
                        ? a.getRealizado()
                        : "Não";
                
                
                model.addRow(new Object[]{
                    a.getIdAgenda(),
                    dataStr,
                    horaStr,
                    clienteStr,
                    manicureStr,
                    servicoStr,
                    valorStr,
                    realizadoStr
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar agendamentos: " + e.getMessage());
        }
    }
    
    
    
    // Preencher Tabela de Produtos
    public void preencherTabelaProdutos(List<Produtos>produtos){
    String columns[] = {"ID","Nome","Marca","Categoria","Quantidade"};
    
    if(produtos != null){
        String dados[][] = new String [produtos.size()][columns.length];
        int i = 0;
        for(Produtos p : produtos){
            dados[i] = new String[]{
               String.valueOf(p.getIdProdutos()),
                p.getNome(),
                p.getMarca(),
                p.getCategoria(),
               p.getQuantidade()!= null ? String.valueOf(p.getQuantidade()) :""
            };
            i++;
            }
        DefaultTableModel model = new DefaultTableModel(dados,columns);
        tblProdutos.setModel(model);
        }
    }
    
    
    
    // Preencher Tabela de Clientes
    public void preencherTabelaClientes(List<Cliente> cliente){
    String columns[] = {"ID","Nome","Gmail","Telefone"};
    
    if(cliente != null){
        String dados[][] = new String [cliente.size()][columns.length];
        int i = 0;
        for (Cliente c : cliente){
            dados[i] = new String[]{
                String.valueOf(c.getIdCliente()),
                c.getNome(),
                c.getGmail(),
                c.getTelefone(),  
            };
            i++;
        }
        DefaultTableModel model = new DefaultTableModel(dados,columns);
        tblClientes.setModel(model);
    }
}
    


}
